//! Regenerates `zig/render/particle_colors.zig` from the exported sprite atlases at build time.
//!
//! For every 16x16 atlas tile, collects the UNIQUE fully-opaque texel colors after compositing with mask
//! (the shader multiplies them; see fs_entity() in src/shader.wgsl),
//! converts each to OKLCH, and emits them as raw Zig arrays indexed CSR-style per tile.
//!
//! Guarded by a content hash of both PNGs so this host tool is not rebuilt/rerun on unrelated changes.
const std = @import("std");

const Bitmap = @import("png/png_to_binary.zig").Bitmap;
const ColorRgba = @import("visual/color_rgba.zig").ColorRgba;

const MAIN_PNG_PATH = "public/assets/main.png";
const MASK_PNG_PATH = "public/assets/mainMasked.png";
const OUTPUT_PATH = "zig/render/particle_colors.zig";

/// Atlas tile edge length in pixels (all sprites are 16x16).
const TILE_SIZE = 16;

pub fn main(init: std.process.Init) !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const cwd = std.Io.Dir.cwd();
    var main_bmp = try loadPng(init.io, allocator, MAIN_PNG_PATH);
    var mask_bmp = try loadPng(init.io, allocator, MASK_PNG_PATH);

    if (main_bmp.width != mask_bmp.width or main_bmp.height != mask_bmp.height)
        return error.AtlasDimensionMismatch;
    if (main_bmp.width % TILE_SIZE != 0 or main_bmp.height % TILE_SIZE != 0)
        return error.AtlasNotTileAligned;

    const tiles_x = main_bmp.width / TILE_SIZE;
    const tiles_y = main_bmp.height / TILE_SIZE;
    const tile_count: usize = @as(usize, tiles_x) * @as(usize, tiles_y);

    // CSR layout: offsets[i]..offsets[i+1] is tile i's slice into the flat color list.
    var offsets = try allocator.alloc(u32, tile_count + 1);
    var all_colors = try std.ArrayListUnmanaged(ColorRgba).initCapacity(allocator, tile_count * 20);

    // Scratch dedup list; a 16x16 tile can hold at most 256 unique colors.
    var unique: [TILE_SIZE * TILE_SIZE]ColorRgba = undefined;

    offsets[0] = 0;
    for (0..tile_count) |tile| {
        const tx: u32 = @intCast((tile % tiles_x) * TILE_SIZE);
        const ty: u32 = @intCast((tile / tiles_x) * TILE_SIZE);

        var unique_len: usize = 0;
        for (0..TILE_SIZE) |py| {
            for (0..TILE_SIZE) |px| {
                const composited = compositeTexel(
                    main_bmp.getPixel(tx + @as(u32, @intCast(px)), ty + @as(u32, @intCast(py))),
                    mask_bmp.getPixel(tx + @as(u32, @intCast(px)), ty + @as(u32, @intCast(py))),
                );
                // Particles only sample fully-opaque texels; antialiased or empty ones are skipped.
                if (!composited.isOpaque()) continue;

                const already_seen = for (unique[0..unique_len]) |seen| {
                    if (seen.eql(composited)) break true;
                } else false;
                if (!already_seen) {
                    unique[unique_len] = composited;
                    unique_len += 1;
                }
            }
        }

        // Canonical ascending order keeps the generated file stable across pixel rearrangements.
        std.mem.sort(ColorRgba, unique[0..unique_len], {}, colorLessThan);
        try all_colors.appendSlice(allocator, unique[0..unique_len]);
        offsets[tile + 1] = @intCast(all_colors.items.len);
    }

    // u16 offsets keep the table compact; 256 unique colors per tile can't realistically overflow
    // this, but assert instead of silently truncating.
    if (all_colors.items.len > std.math.maxInt(u16)) return error.TooManyColors;

    // Render the generated Zig source.
    var bw = std.Io.Writer.Allocating.init(allocator);
    defer bw.deinit();
    const writer = &bw.writer;

    try writer.print(
        \\//! Auto-generated by zig/generate_particles.zig (runs during `zig build`); do NOT edit by hand.
        \\//! Unique fully-opaque colors of every 16x16 sprite-atlas tile, composited as main.png * mainMasked.png
        \\//! to match `fs_entity()` in src/shader.wgsl, then converted to OKLCH.
        \\//! Each entry is (L, C, H in radians, A in 0-1) and can be used directly as an entity `lcha`
        \\//! tint over a white sprite such as `.particle`.
        \\
        \\/// Number of 16x16 tiles in the sprite atlas (row-major, {d} per row).
        \\pub const TILE_COUNT: usize = {d};
        \\
        \\/// CSR offsets into `colors`: tile `i` owns `colors[tile_offsets[i]..tile_offsets[i + 1]]`.
        \\pub const tile_offsets = [TILE_COUNT + 1]u16{{
        \\
    , .{ tiles_x, tile_count });

    // 16 offsets per row; zig fmt column-aligns multi-element rows, so pad every cell to the
    // widest offset (the final one, since offsets are non-decreasing) plus a comma and a space.
    const cell_width = decimalWidth(offsets[tile_count]) + 2;
    for (offsets, 0..) |offset, i| {
        if (i % 16 == 0) try writer.writeAll("    ");
        if (i % 16 == 15 or i == offsets.len - 1) {
            try writer.print("{d},\n", .{offset});
        } else {
            try writer.print("{d},", .{offset});
            try writer.splatByteAll(' ', cell_width - decimalWidth(offset) - 1);
        }
    }

    try writer.print(
        \\}};
        \\
        \\/// Unique tile colors as OKLCH+alpha (see file docs). {d} colors total.
        \\pub const colors = [_][4]f32{{
        \\
    , .{all_colors.items.len});

    for (all_colors.items) |color| {
        const lcha = color.toOklch();
        try writer.print("    .{{ {d:.4}, {d:.4}, {d:.4}, {d:.4} }}, // #{x:0>6}\n", .{
            lcha[0],                    lcha[1], lcha[2], lcha[3],
            // RGB hex of the source color for debugging (word is little-endian ABGR)
            @byteSwap(color.word) >> 8,
        });
    }
    try writer.writeAll("};\n");

    // Only touch the file when the content actually changes, so the dev file-watcher does not churn.
    const new_content = bw.written();
    const old_content = cwd.readFileAlloc(init.io, OUTPUT_PATH, allocator, .unlimited) catch "";
    if (!std.mem.eql(u8, new_content, old_content)) {
        try cwd.writeFile(init.io, .{ .sub_path = OUTPUT_PATH, .data = new_content });
    }

    // Update the content-hash cache so build.zig can skip rebuilding this tool next time!
    const args = try init.minimal.args.toSlice(allocator);
    if (args.len < 4) return;
    const cache_root = args[1];
    const cache_path = args[2];
    const current_hash_hex = args[3];
    cwd.createDirPath(init.io, cache_root) catch {};
    cwd.writeFile(init.io, .{ .sub_path = cache_path, .data = current_hash_hex }) catch {};
}

/// Reads and decodes one PNG through the shared png_to_binary decoder.
fn loadPng(io: std.Io, allocator: std.mem.Allocator, path: []const u8) !Bitmap {
    const data = try std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .unlimited);
    defer allocator.free(data);
    return Bitmap.fromPngData(allocator, data);
}

/// Composites one atlas texel the same way the entity shader does: channel-wise multiply of
/// main and mask (both alpha and RGB), with u8 math mirroring the shader's normalized floats.
fn compositeTexel(tex: ColorRgba, mask: ColorRgba) ColorRgba {
    return ColorRgba.init(
        @intCast((@as(u16, tex.channels.r) * mask.channels.r) / 255),
        @intCast((@as(u16, tex.channels.g) * mask.channels.g) / 255),
        @intCast((@as(u16, tex.channels.b) * mask.channels.b) / 255),
        @intCast((@as(u16, tex.channels.a) * mask.channels.a) / 255),
    );
}

fn colorLessThan(_: void, a: ColorRgba, b: ColorRgba) bool {
    return a.word < b.word;
}

/// Number of characters needed to print `value` in decimal.
fn decimalWidth(value: u32) usize {
    var width: usize = 1;
    var v = value;
    while (v >= 10) : (v /= 10) width += 1;
    return width;
}
